import type { ListingStatus } from '@ethanel/contracts/listing';
import type {
  KenyaCounty,
  MarketplaceAmenity,
  MarketplaceIntent,
  MarketplaceType,
} from '@ethanel/contracts/marketplace-search';

import type { ImageSlotId } from '@/content/images';

/**
 * Original sample listings for the marketplace, written in the style of Kenyan property sites
 * after a reference pass (neighbourhoods, unit types, price bands, amenity wording). Nothing
 * here is a real advert, address, organization or photo; every card is labelled "sample".
 * listing-svc replaces this module; the shape is what its /v1/listings returns.
 * `priceKes` is a whole-shilling display figure for filtering samples only (Q-19).
 */
export interface SampleListing {
  readonly id: string;
  readonly intent: MarketplaceIntent;
  readonly type: MarketplaceType;
  readonly county: KenyaCounty;
  /** Town, estate or road; free-text search matches against this and `location`. */
  readonly area: string;
  readonly status: ListingStatus;
  /** ISO date, Africa/Nairobi. */
  readonly publishedAt: string;
  readonly coordinates: { lat: number; lng: number };
  readonly chip: string;
  readonly priceKes: number;
  readonly title: string;
  readonly meta: string;
  readonly location: string;
  readonly agency: string;
  readonly beds: number | null;
  readonly amenities: readonly MarketplaceAmenity[];
  readonly photo: ImageSlotId;
}

/** Fictional managing organizations, reused consistently across listings. */
const A = {
  riverside: 'Riverside Lettings',
  ridgeways: 'Ridgeways Property Care',
  mavoko: 'Mavoko Homes',
  stays: 'Nairobi Stays Co.',
  rongai: 'Rongai Lettings',
  kiambuHomes: 'Kiambu Homes Agency',
  savannah: 'Savannah Land Co.',
  bahari: 'Bahari Coast Properties',
  lakeside: 'Lakeside Estates Kisumu',
  highlands: 'Highlands Property Care',
  rift: 'Rift Valley Homes',
  mtKenya: 'Mount Kenya Land Co.',
  westernGate: 'Western Gate Properties',
  pwani: 'Pwani Stays',
} as const;

export const sampleListings: readonly SampleListing[] = [
  // ---- Rentals (monthly) ----
  {
    id: 'rl-kilimani-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'nairobi',
    area: 'Kilimani',
    status: 'vacant',
    publishedAt: '2026-09-15',
    coordinates: { lat: -1.2921, lng: 36.7856 },
    chip: '2-bed unit · To let',
    priceKes: 45_000,
    title: 'Bright two-bedroom with balcony, borehole water',
    meta: '2 bed · 2 bath · 90 m²',
    location: 'Kilimani, Nairobi',
    agency: A.riverside,
    beds: 2,
    amenities: ['water', 'parking'],
    photo: 'listing-nairobi-apartment',
  },
  {
    id: 'rl-westlands-bedsitter',
    intent: 'rent',
    type: 'unit-bedsitter',
    county: 'nairobi',
    area: 'Westlands',
    status: 'vacant',
    publishedAt: '2026-09-14',
    coordinates: { lat: -1.2676, lng: 36.8108 },
    chip: 'Bedsitter · To let',
    priceKes: 18_000,
    title: 'Furnished bedsitter, water and Wi-Fi included',
    meta: 'Studio · 1 bath · 28 m²',
    location: 'Westlands, Nairobi',
    agency: A.riverside,
    beds: null,
    amenities: ['water'],
    photo: 'listing-bedsitter',
  },
  {
    id: 'rl-kileleshwa-3bed',
    intent: 'rent',
    type: 'unit-3bed-plus',
    county: 'nairobi',
    area: 'Kileleshwa',
    status: 'booked',
    publishedAt: '2026-09-11',
    coordinates: { lat: -1.2833, lng: 36.7833 },
    chip: '3-bed unit · To let',
    priceKes: 85_000,
    title: 'Three-bedroom all ensuite with DSQ, lift and backup generator',
    meta: '3 bed · 3 bath · DSQ · 160 m²',
    location: 'Kileleshwa, Nairobi',
    agency: A.riverside,
    beds: 3,
    amenities: ['power', 'parking', 'gated'],
    photo: 'listing-nairobi-apartment',
  },
  {
    id: 'rl-kasarani-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    county: 'nairobi',
    area: 'Kasarani',
    status: 'vacant',
    publishedAt: '2026-09-12',
    coordinates: { lat: -1.2205, lng: 36.8977 },
    chip: '1-bed unit · To let',
    priceKes: 15_000,
    title: 'One-bedroom near the Thika Road stage, prepaid meter',
    meta: '1 bed · 1 bath · 45 m²',
    location: 'Kasarani, Nairobi',
    agency: A.ridgeways,
    beds: 1,
    amenities: ['matatu', 'water'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'rl-langata-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'nairobi',
    area: "Lang'ata",
    status: 'vacant',
    publishedAt: '2026-09-09',
    coordinates: { lat: -1.3403, lng: 36.7659 },
    chip: '2-bed unit · To let',
    priceKes: 38_000,
    title: 'Two-bedroom master ensuite in a gated court with parking',
    meta: '2 bed · 2 bath · 85 m²',
    location: "Lang'ata, Nairobi",
    agency: A.riverside,
    beds: 2,
    amenities: ['gated', 'parking'],
    photo: 'listing-nairobi-apartment',
  },
  {
    id: 'rl-southb-studio',
    intent: 'rent',
    type: 'unit-bedsitter',
    county: 'nairobi',
    area: 'South B',
    status: 'let',
    publishedAt: '2026-08-28',
    coordinates: { lat: -1.3133, lng: 36.8333 },
    chip: 'Studio · To let',
    priceKes: 22_000,
    title: 'Modern studio with fitted kitchen, 24-hour security',
    meta: 'Studio · 1 bath · 32 m²',
    location: 'South B, Nairobi',
    agency: A.ridgeways,
    beds: null,
    amenities: ['gated', 'water'],
    photo: 'listing-bedsitter',
  },
  {
    id: 'rp-ruaka-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    county: 'kiambu',
    area: 'Ruaka',
    status: 'vacant',
    publishedAt: '2026-09-13',
    coordinates: { lat: -1.2085, lng: 36.7797 },
    chip: '1-bed unit · To let',
    priceKes: 25_000,
    title: 'One-bedroom in a gated court, near matatu route',
    meta: '1 bed · 1 bath · 48 m²',
    location: 'Ruaka, Kiambu',
    agency: A.ridgeways,
    beds: 1,
    amenities: ['gated', 'matatu'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'kh-thika-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'kiambu',
    area: 'Thika',
    status: 'vacant',
    publishedAt: '2026-09-07',
    coordinates: { lat: -1.0332, lng: 37.0693 },
    chip: '2-bed unit · To let',
    priceKes: 20_000,
    title: 'Two-bedroom off Garissa Road with borehole and parking',
    meta: '2 bed · 1 bath · 70 m²',
    location: 'Thika, Kiambu',
    agency: A.kiambuHomes,
    beds: 2,
    amenities: ['water', 'parking'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'kh-kikuyu-3bed',
    intent: 'rent',
    type: 'home-standalone',
    county: 'kiambu',
    area: 'Kikuyu',
    status: 'under-offer',
    publishedAt: '2026-09-02',
    coordinates: { lat: -1.2461, lng: 36.6631 },
    chip: '3-bed home · To let',
    priceKes: 55_000,
    title: 'Three-bedroom bungalow on a quarter acre with a kitchen garden',
    meta: '3 bed · 2 bath · 1/4 acre',
    location: 'Kikuyu, Kiambu',
    agency: A.kiambuHomes,
    beds: 3,
    amenities: ['water', 'parking', 'gated'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'mh-syokimau-3bed',
    intent: 'rent',
    type: 'home-maisonette',
    county: 'machakos',
    area: 'Syokimau',
    status: 'vacant',
    publishedAt: '2026-09-10',
    coordinates: { lat: -1.3566, lng: 36.9269 },
    chip: '3-bed home · To let',
    priceKes: 65_000,
    title: 'Three-bedroom maisonette with parking and backup power',
    meta: '3 bed · 3 bath · 140 m²',
    location: 'Syokimau, Machakos',
    agency: A.mavoko,
    beds: 3,
    amenities: ['parking', 'power', 'gated'],
    photo: 'listing-maisonette-gated',
  },
  {
    id: 'mh-athi-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'machakos',
    area: 'Athi River',
    status: 'vacant',
    publishedAt: '2026-09-04',
    coordinates: { lat: -1.456, lng: 36.978 },
    chip: '2-bed unit · To let',
    priceKes: 24_000,
    title: 'Two-bedroom near the SGR station, water seven days a week',
    meta: '2 bed · 1 bath · 72 m²',
    location: 'Athi River, Machakos',
    agency: A.mavoko,
    beds: 2,
    amenities: ['water', 'matatu'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'rg-rongai-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'kajiado',
    area: 'Ongata Rongai',
    status: 'vacant',
    publishedAt: '2026-09-05',
    coordinates: { lat: -1.3936, lng: 36.7627 },
    chip: '2-bed unit · To let',
    priceKes: 38_000,
    title: 'Two-bedroom apartment, gated with 24-hour security',
    meta: '2 bed · 1 bath · 82 m²',
    location: 'Ongata Rongai, Kajiado',
    agency: A.rongai,
    beds: 2,
    amenities: ['gated', 'parking'],
    photo: 'listing-nairobi-apartment',
  },
  {
    id: 'sl-kitengela-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    county: 'kajiado',
    area: 'Kitengela',
    status: 'vacant',
    publishedAt: '2026-08-30',
    coordinates: { lat: -1.475, lng: 36.96 },
    chip: '1-bed unit · To let',
    priceKes: 14_000,
    title: 'One-bedroom off Namanga Road with prepaid token meter',
    meta: '1 bed · 1 bath · 42 m²',
    location: 'Kitengela, Kajiado',
    agency: A.rongai,
    beds: 1,
    amenities: ['water', 'matatu'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'bc-nyali-3bed',
    intent: 'rent',
    type: 'unit-3bed-plus',
    county: 'mombasa',
    area: 'Nyali',
    status: 'vacant',
    publishedAt: '2026-09-14',
    coordinates: { lat: -4.0435, lng: 39.7065 },
    chip: '3-bed unit · To let',
    priceKes: 70_000,
    title: 'Three-bedroom sea-view apartment with pool, gym and lift',
    meta: '3 bed · 3 bath · 150 m²',
    location: 'Nyali, Mombasa',
    agency: A.bahari,
    beds: 3,
    amenities: ['pool', 'gym', 'parking', 'gated'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'bc-bamburi-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'mombasa',
    area: 'Bamburi',
    status: 'vacant',
    publishedAt: '2026-09-08',
    coordinates: { lat: -3.9977, lng: 39.7245 },
    chip: '2-bed unit · To let',
    priceKes: 28_000,
    title: 'Two-bedroom in Bamburi Mwembe Legeza, borehole and standby generator',
    meta: '2 bed · 2 bath · 88 m²',
    location: 'Bamburi, Mombasa',
    agency: A.bahari,
    beds: 2,
    amenities: ['water', 'power'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'ls-milimani-4bed',
    intent: 'rent',
    type: 'home-standalone',
    county: 'kisumu',
    area: 'Milimani',
    status: 'vacant',
    publishedAt: '2026-09-12',
    coordinates: { lat: -0.1022, lng: 34.7617 },
    chip: '4-bed home · To let',
    priceKes: 90_000,
    title: 'Four-bedroom standalone in Milimani with a lake breeze and DSQ',
    meta: '4 bed · 4 bath · DSQ · 1/2 acre',
    location: 'Milimani, Kisumu',
    agency: A.lakeside,
    beds: 4,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'ls-kisumu-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'kisumu',
    area: 'Tom Mboya Estate',
    status: 'vacant',
    publishedAt: '2026-09-06',
    coordinates: { lat: -0.0917, lng: 34.7681 },
    chip: '2-bed unit · To let',
    priceKes: 22_000,
    title: 'Two-bedroom near Kisumu CBD with lift and parking',
    meta: '2 bed · 1 bath · 76 m²',
    location: 'Tom Mboya Estate, Kisumu',
    agency: A.lakeside,
    beds: 2,
    amenities: ['lift', 'parking', 'matatu'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'rv-milimani-nakuru-3bed',
    intent: 'rent',
    type: 'unit-3bed-plus',
    county: 'nakuru',
    area: 'Milimani',
    status: 'booked',
    publishedAt: '2026-09-03',
    coordinates: { lat: -0.2946, lng: 36.0578 },
    chip: '3-bed unit · To let',
    priceKes: 45_000,
    title: 'Three-bedroom in Milimani, Nakuru, with backup generator and lift',
    meta: '3 bed · 2 bath · 130 m²',
    location: 'Milimani, Nakuru',
    agency: A.rift,
    beds: 3,
    amenities: ['power', 'lift', 'parking'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'rv-naivasha-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    county: 'nakuru',
    area: 'Naivasha',
    status: 'vacant',
    publishedAt: '2026-08-31',
    coordinates: { lat: -0.7172, lng: 36.431 },
    chip: '1-bed unit · To let',
    priceKes: 13_000,
    title: 'One-bedroom off Moi South Lake Road, borehole water',
    meta: '1 bed · 1 bath · 40 m²',
    location: 'Naivasha, Nakuru',
    agency: A.rift,
    beds: 1,
    amenities: ['water'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'hp-eldoret-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'uasin-gishu',
    area: 'Elgon View',
    status: 'vacant',
    publishedAt: '2026-09-09',
    coordinates: { lat: 0.5029, lng: 35.2812 },
    chip: '2-bed unit · To let',
    priceKes: 30_000,
    title: 'Two-bedroom in Elgon View, Eldoret, gated with ample parking',
    meta: '2 bed · 2 bath · 95 m²',
    location: 'Elgon View, Eldoret',
    agency: A.highlands,
    beds: 2,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'hp-nyeri-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    county: 'nyeri',
    area: 'Kingongo',
    status: 'vacant',
    publishedAt: '2026-09-01',
    coordinates: { lat: -0.4197, lng: 36.9553 },
    chip: '1-bed unit · To let',
    priceKes: 12_000,
    title: 'One-bedroom in Kingongo, Nyeri, near the matatu stage',
    meta: '1 bed · 1 bath · 44 m²',
    location: 'Kingongo, Nyeri',
    agency: A.highlands,
    beds: 1,
    amenities: ['matatu', 'water'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'mk-meru-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'meru',
    area: 'Makutano',
    status: 'vacant',
    publishedAt: '2026-08-27',
    coordinates: { lat: 0.0625, lng: 37.6516 },
    chip: '2-bed unit · To let',
    priceKes: 16_000,
    title: 'Two-bedroom in Makutano, Meru, with borehole and parking',
    meta: '2 bed · 1 bath · 70 m²',
    location: 'Makutano, Meru',
    agency: A.mtKenya,
    beds: 2,
    amenities: ['water', 'parking'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'mk-nanyuki-3bed',
    intent: 'rent',
    type: 'home-standalone',
    county: 'laikipia',
    area: 'Nanyuki',
    status: 'vacant',
    publishedAt: '2026-09-11',
    coordinates: { lat: 0.0167, lng: 37.0728 },
    chip: '3-bed home · To let',
    priceKes: 60_000,
    title: 'Three-bedroom standalone on a half acre with Mount Kenya views',
    meta: '3 bed · 2 bath · 1/2 acre',
    location: 'Nanyuki, Laikipia',
    agency: A.mtKenya,
    beds: 3,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-bungalow-upcountry',
  },
  {
    id: 'wg-kakamega-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'kakamega',
    area: 'Amalemba',
    status: 'vacant',
    publishedAt: '2026-08-25',
    coordinates: { lat: 0.2827, lng: 34.7519 },
    chip: '2-bed unit · To let',
    priceKes: 15_000,
    title: 'Two-bedroom in Amalemba, Kakamega, with 24-hour water',
    meta: '2 bed · 1 bath · 68 m²',
    location: 'Amalemba, Kakamega',
    agency: A.westernGate,
    beds: 2,
    amenities: ['water'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'bc-kilifi-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    county: 'kilifi',
    area: 'Kilifi town',
    status: 'vacant',
    publishedAt: '2026-09-02',
    coordinates: { lat: -3.6305, lng: 39.8499 },
    chip: '2-bed unit · To let',
    priceKes: 25_000,
    title: 'Two-bedroom five minutes from Kilifi creek, borehole and parking',
    meta: '2 bed · 2 bath · 84 m²',
    location: 'Kilifi town, Kilifi',
    agency: A.bahari,
    beds: 2,
    amenities: ['water', 'parking'],
    photo: 'listing-apartment-coast',
  },

  // ---- For sale (homes and units) ----
  {
    id: 'kh-ruiru-3bed',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'kiambu',
    area: 'Ruiru',
    status: 'vacant',
    publishedAt: '2026-09-14',
    coordinates: { lat: -1.145, lng: 36.9588 },
    chip: '3-bed home · For sale',
    priceKes: 9_800_000,
    title: 'Three-bedroom maisonette in a gated court',
    meta: '3 bed · 3 bath · 1/8 acre',
    location: 'Ruiru, Kiambu',
    agency: A.kiambuHomes,
    beds: 3,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-maisonette-gated',
  },
  {
    id: 'kh-thika-2bed-sale',
    intent: 'sale',
    type: 'unit-2bed',
    county: 'kiambu',
    area: 'Thika',
    status: 'vacant',
    publishedAt: '2026-09-10',
    coordinates: { lat: -1.0397, lng: 37.0834 },
    chip: '2-bed unit · For sale',
    priceKes: 5_200_000,
    title: 'Two-bedroom apartment, ready title, lift and parking',
    meta: '2 bed · 2 bath · 78 m²',
    location: 'Thika, Kiambu',
    agency: A.kiambuHomes,
    beds: 2,
    amenities: ['lift', 'parking'],
    photo: 'listing-apartment-town',
  },
  {
    id: 'kh-juja-4bed',
    intent: 'sale',
    type: 'home-standalone',
    county: 'kiambu',
    area: 'Juja',
    status: 'under-offer',
    publishedAt: '2026-08-29',
    coordinates: { lat: -1.102, lng: 37.014 },
    chip: '4-bed home · For sale',
    priceKes: 16_500_000,
    title: 'Four-bedroom standalone on a quarter acre in a controlled estate',
    meta: '4 bed · 4 bath · DSQ · 1/4 acre',
    location: 'Juja, Kiambu',
    agency: A.kiambuHomes,
    beds: 4,
    amenities: ['gated', 'parking', 'water', 'power'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'rg-rongai-4bed',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'kajiado',
    area: 'Ongata Rongai',
    status: 'vacant',
    publishedAt: '2026-09-06',
    coordinates: { lat: -1.39, lng: 36.77 },
    chip: '4-bed home · For sale',
    priceKes: 14_500_000,
    title: 'Four-bedroom townhouse with DSQ and garden',
    meta: '4 bed · 4 bath · 1/4 acre',
    location: 'Ongata Rongai, Kajiado',
    agency: A.rongai,
    beds: 4,
    amenities: ['gated', 'parking', 'power'],
    photo: 'listing-townhouse',
  },
  {
    id: 'sl-kitengela-3bed',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'kajiado',
    area: 'Kitengela',
    status: 'vacant',
    publishedAt: '2026-09-01',
    coordinates: { lat: -1.4795, lng: 36.9576 },
    chip: '3-bed home · For sale',
    priceKes: 7_900_000,
    title: 'Three-bedroom maisonette in Kitengela with borehole and solar water heating',
    meta: '3 bed · 2 bath · 1/8 acre',
    location: 'Kitengela, Kajiado',
    agency: A.savannah,
    beds: 3,
    amenities: ['water', 'gated'],
    photo: 'listing-maisonette-gated',
  },
  {
    id: 'rl-kilimani-3bed-sale',
    intent: 'sale',
    type: 'unit-3bed-plus',
    county: 'nairobi',
    area: 'Kilimani',
    status: 'vacant',
    publishedAt: '2026-09-13',
    coordinates: { lat: -1.2895, lng: 36.7902 },
    chip: '3-bed unit · For sale',
    priceKes: 18_500_000,
    title: 'Three-bedroom all ensuite with DSQ, gym and pool in Kilimani',
    meta: '3 bed · 3 bath · DSQ · 170 m²',
    location: 'Kilimani, Nairobi',
    agency: A.riverside,
    beds: 3,
    amenities: ['gym', 'pool', 'lift', 'parking'],
    photo: 'listing-nairobi-apartment',
  },
  {
    id: 'rl-karen-5bed',
    intent: 'sale',
    type: 'home-standalone',
    county: 'nairobi',
    area: 'Karen',
    status: 'vacant',
    publishedAt: '2026-08-26',
    coordinates: { lat: -1.3197, lng: 36.7062 },
    chip: '5-bed home · For sale',
    priceKes: 68_000_000,
    title: 'Five-bedroom home on half an acre in Karen with mature garden',
    meta: '5 bed · 5 bath · DSQ · 1/2 acre',
    location: 'Karen, Nairobi',
    agency: A.riverside,
    beds: 5,
    amenities: ['gated', 'parking', 'water', 'power'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'mh-syokimau-4bed-sale',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'machakos',
    area: 'Syokimau',
    status: 'sold',
    publishedAt: '2026-08-20',
    coordinates: { lat: -1.36, lng: 36.93 },
    chip: '4-bed home · For sale',
    priceKes: 13_800_000,
    title: 'Four-bedroom townhouse in a gated estate off Mombasa Road',
    meta: '4 bed · 3 bath · 1/8 acre',
    location: 'Syokimau, Machakos',
    agency: A.mavoko,
    beds: 4,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-townhouse',
  },
  {
    id: 'bc-nyali-3bed-sale',
    intent: 'sale',
    type: 'unit-3bed-plus',
    county: 'mombasa',
    area: 'Nyali',
    status: 'vacant',
    publishedAt: '2026-09-09',
    coordinates: { lat: -4.05, lng: 39.71 },
    chip: '3-bed unit · For sale',
    priceKes: 14_500_000,
    title: 'Three-bedroom ocean-view apartment in Nyali with pool and lift',
    meta: '3 bed · 3 bath · 145 m²',
    location: 'Nyali, Mombasa',
    agency: A.bahari,
    beds: 3,
    amenities: ['pool', 'lift', 'parking', 'gated'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'bc-diani-2bed-sale',
    intent: 'sale',
    type: 'unit-2bed',
    county: 'kwale',
    area: 'Diani',
    status: 'vacant',
    publishedAt: '2026-09-04',
    coordinates: { lat: -4.2797, lng: 39.5895 },
    chip: '2-bed unit · For sale',
    priceKes: 9_200_000,
    title: 'Two-bedroom beach apartment in Diani, furnished, with shared pool',
    meta: '2 bed · 2 bath · 96 m²',
    location: 'Diani, Kwale',
    agency: A.pwani,
    beds: 2,
    amenities: ['pool', 'gated', 'parking'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'ls-kisumu-3bed-sale',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'kisumu',
    area: 'Riat Hills',
    status: 'vacant',
    publishedAt: '2026-09-07',
    coordinates: { lat: -0.0533, lng: 34.7301 },
    chip: '3-bed home · For sale',
    priceKes: 11_000_000,
    title: 'Three-bedroom maisonette in Riat Hills with a view over Lake Victoria',
    meta: '3 bed · 3 bath · 1/8 acre',
    location: 'Riat Hills, Kisumu',
    agency: A.lakeside,
    beds: 3,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-maisonette-gated',
  },
  {
    id: 'rv-nakuru-5bed',
    intent: 'sale',
    type: 'home-standalone',
    county: 'nakuru',
    area: 'Milimani',
    status: 'vacant',
    publishedAt: '2026-08-24',
    coordinates: { lat: -0.297, lng: 36.06 },
    chip: '5-bed home · For sale',
    priceKes: 35_000_000,
    title: 'Five-bedroom standalone in Milimani, Nakuru, on a quarter acre',
    meta: '5 bed · 4 bath · DSQ · 1/4 acre',
    location: 'Milimani, Nakuru',
    agency: A.rift,
    beds: 5,
    amenities: ['gated', 'parking', 'water', 'power'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'hp-eldoret-3bed-sale',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'uasin-gishu',
    area: 'Kapsoya',
    status: 'vacant',
    publishedAt: '2026-09-03',
    coordinates: { lat: 0.5241, lng: 35.3049 },
    chip: '3-bed home · For sale',
    priceKes: 8_500_000,
    title: 'Three-bedroom maisonette in Kapsoya, Eldoret, in a gated court',
    meta: '3 bed · 2 bath · 1/8 acre',
    location: 'Kapsoya, Eldoret',
    agency: A.highlands,
    beds: 3,
    amenities: ['gated', 'parking', 'water'],
    photo: 'listing-maisonette-gated',
  },
  {
    id: 'hp-nyeri-4bed-sale',
    intent: 'sale',
    type: 'home-standalone',
    county: 'nyeri',
    area: 'Kamakwa',
    status: 'vacant',
    publishedAt: '2026-08-22',
    coordinates: { lat: -0.4, lng: 36.94 },
    chip: '4-bed home · For sale',
    priceKes: 12_000_000,
    title: 'Four-bedroom bungalow in Kamakwa, Nyeri, on a quarter acre with tea bushes',
    meta: '4 bed · 3 bath · 1/4 acre',
    location: 'Kamakwa, Nyeri',
    agency: A.highlands,
    beds: 4,
    amenities: ['water', 'parking'],
    photo: 'listing-bungalow-upcountry',
  },
  {
    id: 'mk-nanyuki-3bed-sale',
    intent: 'sale',
    type: 'home-standalone',
    county: 'laikipia',
    area: 'Nanyuki',
    status: 'coming-soon',
    publishedAt: '2026-09-15',
    coordinates: { lat: 0.02, lng: 37.08 },
    chip: '3-bed home · For sale',
    priceKes: 19_500_000,
    title: 'Three-bedroom cottage on an acre outside Nanyuki with Mount Kenya views',
    meta: '3 bed · 3 bath · 1 acre',
    location: 'Nanyuki, Laikipia',
    agency: A.mtKenya,
    beds: 3,
    amenities: ['water', 'gated'],
    photo: 'listing-nanyuki-view',
  },
  {
    id: 'mk-meru-3bed-sale',
    intent: 'sale',
    type: 'home-maisonette',
    county: 'meru',
    area: 'Milimani',
    status: 'vacant',
    publishedAt: '2026-08-28',
    coordinates: { lat: 0.0463, lng: 37.6559 },
    chip: '3-bed home · For sale',
    priceKes: 7_200_000,
    title: 'Three-bedroom maisonette in Milimani, Meru, with borehole',
    meta: '3 bed · 2 bath · 1/8 acre',
    location: 'Milimani, Meru',
    agency: A.mtKenya,
    beds: 3,
    amenities: ['water', 'parking'],
    photo: 'listing-maisonette-gated',
  },

  // ---- Land (plots for sale) ----
  {
    id: 'sl-kitengela-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kajiado',
    area: 'Kitengela',
    status: 'vacant',
    publishedAt: '2026-09-15',
    coordinates: { lat: -1.475, lng: 36.96 },
    chip: 'Plot · For sale',
    priceKes: 2_400_000,
    title: '1/8 acre residential plot, tarmac access',
    meta: '1/8 acre · residential · ready title',
    location: 'Kitengela, Kajiado',
    agency: A.savannah,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-tarmac',
  },
  {
    id: 'sl-kangundo-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'machakos',
    area: 'Kangundo Road',
    status: 'vacant',
    publishedAt: '2026-09-08',
    coordinates: { lat: -1.25, lng: 37.11 },
    chip: 'Plot · For sale',
    priceKes: 1_650_000,
    title: '1/4 acre plot with water and power on the boundary',
    meta: '1/4 acre · residential · ready title',
    location: 'Kangundo Road, Machakos',
    agency: A.savannah,
    beds: null,
    amenities: ['water', 'power'],
    photo: 'listing-plot-estate',
  },
  {
    id: 'kh-ruiru-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kiambu',
    area: 'Ruiru',
    status: 'vacant',
    publishedAt: '2026-09-04',
    coordinates: { lat: -1.14, lng: 36.97 },
    chip: 'Plot · For sale',
    priceKes: 4_900_000,
    title: '50 by 100 plot in a controlled estate',
    meta: '50×100 · residential · ready title',
    location: 'Ruiru, Kiambu',
    agency: A.kiambuHomes,
    beds: null,
    amenities: ['gated', 'tarmac'],
    photo: 'listing-plot-estate',
  },
  {
    id: 'sl-joska-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'machakos',
    area: 'Joska',
    status: 'vacant',
    publishedAt: '2026-08-30',
    coordinates: { lat: -1.2694, lng: 37.1697 },
    chip: 'Plot · For sale',
    priceKes: 950_000,
    title: '50 by 100 plot in Joska, second row from the tarmac',
    meta: '50×100 · residential · ready title',
    location: 'Joska, Machakos',
    agency: A.savannah,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-tarmac',
  },
  {
    id: 'sl-isinya-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kajiado',
    area: 'Isinya',
    status: 'sold',
    publishedAt: '2026-08-18',
    coordinates: { lat: -1.67, lng: 36.85 },
    chip: 'Plot · For sale',
    priceKes: 750_000,
    title: '1/8 acre plot in Isinya with beacons in place and a fenced boundary',
    meta: '1/8 acre · residential · ready title',
    location: 'Isinya, Kajiado',
    agency: A.savannah,
    beds: null,
    amenities: [],
    photo: 'listing-plot-estate',
  },
  {
    id: 'bc-kilifi-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kilifi',
    area: 'Vipingo',
    status: 'vacant',
    publishedAt: '2026-09-11',
    coordinates: { lat: -3.8027, lng: 39.7886 },
    chip: 'Plot · For sale',
    priceKes: 3_800_000,
    title: '1/4 acre plot in Vipingo, a short walk from the beach',
    meta: '1/4 acre · residential · ready title',
    location: 'Vipingo, Kilifi',
    agency: A.bahari,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-beach-plot',
  },
  {
    id: 'bc-malindi-acre',
    intent: 'land',
    type: 'plot-residential',
    county: 'kilifi',
    area: 'Malindi',
    status: 'vacant',
    publishedAt: '2026-08-27',
    coordinates: { lat: -3.2192, lng: 40.1169 },
    chip: 'Land · For sale',
    priceKes: 1_650_000,
    title: 'One acre off the Malindi–Sala Gate road with water on site',
    meta: '1 acre · residential · ready title',
    location: 'Malindi, Kilifi',
    agency: A.bahari,
    beds: null,
    amenities: ['water'],
    photo: 'listing-beach-plot',
  },
  {
    id: 'ls-kisumu-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kisumu',
    area: 'Mamboleo',
    status: 'vacant',
    publishedAt: '2026-09-05',
    coordinates: { lat: -0.0619, lng: 34.7806 },
    chip: 'Plot · For sale',
    priceKes: 2_100_000,
    title: '50 by 100 plot in Mamboleo, Kisumu, with tarmac access',
    meta: '50×100 · residential · ready title',
    location: 'Mamboleo, Kisumu',
    agency: A.lakeside,
    beds: null,
    amenities: ['tarmac', 'water'],
    photo: 'listing-lakeside',
  },
  {
    id: 'rv-nakuru-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'nakuru',
    area: 'Pipeline',
    status: 'vacant',
    publishedAt: '2026-09-02',
    coordinates: { lat: -0.3277, lng: 36.1108 },
    chip: 'Plot · For sale',
    priceKes: 1_900_000,
    title: '50 by 100 plot in Pipeline, Nakuru, near the Nairobi highway',
    meta: '50×100 · residential · ready title',
    location: 'Pipeline, Nakuru',
    agency: A.rift,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-tarmac',
  },
  {
    id: 'rv-naivasha-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'nakuru',
    area: 'Naivasha',
    status: 'vacant',
    publishedAt: '2026-08-23',
    coordinates: { lat: -0.75, lng: 36.43 },
    chip: 'Plot · For sale',
    priceKes: 1_250_000,
    title: '1/8 acre plot on the Naivasha–Moi South Lake Road side, beacons in place',
    meta: '1/8 acre · residential · ready title',
    location: 'Naivasha, Nakuru',
    agency: A.rift,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-estate',
  },
  {
    id: 'hp-eldoret-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'uasin-gishu',
    area: 'Kapseret',
    status: 'vacant',
    publishedAt: '2026-09-10',
    coordinates: { lat: 0.4661, lng: 35.2106 },
    chip: 'Plot · For sale',
    priceKes: 1_400_000,
    title: '50 by 100 plot in Kapseret near the Eldoret bypass',
    meta: '50×100 · residential · ready title',
    location: 'Kapseret, Eldoret',
    agency: A.highlands,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-tarmac',
  },
  {
    id: 'mk-nanyuki-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'laikipia',
    area: 'Nanyuki',
    status: 'vacant',
    publishedAt: '2026-09-13',
    coordinates: { lat: 0.04, lng: 37.05 },
    chip: 'Plot · For sale',
    priceKes: 1_100_000,
    title: '1/8 acre plot outside Nanyuki with Mount Kenya views, ready title',
    meta: '1/8 acre · residential · ready title',
    location: 'Nanyuki, Laikipia',
    agency: A.mtKenya,
    beds: null,
    amenities: [],
    photo: 'listing-nanyuki-view',
  },
  {
    id: 'mk-meru-commercial-plot',
    intent: 'land',
    type: 'plot-commercial',
    county: 'meru',
    area: 'Meru town',
    status: 'vacant',
    publishedAt: '2026-08-21',
    coordinates: { lat: 0.0479, lng: 37.6491 },
    chip: 'Commercial plot · For sale',
    priceKes: 6_500_000,
    title: 'Quarter-acre commercial plot on the Meru–Nanyuki highway frontage',
    meta: '1/4 acre · commercial · ready title',
    location: 'Meru town, Meru',
    agency: A.mtKenya,
    beds: null,
    amenities: ['tarmac', 'power'],
    photo: 'listing-commercial-plot',
  },
  {
    id: 'hp-nyeri-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'nyeri',
    area: 'Kiganjo',
    status: 'under-offer',
    publishedAt: '2026-08-19',
    coordinates: { lat: -0.3667, lng: 37.0 },
    chip: 'Plot · For sale',
    priceKes: 850_000,
    title: '1/8 acre plot in Kiganjo, Nyeri, with water and power nearby',
    meta: '1/8 acre · residential · ready title',
    location: 'Kiganjo, Nyeri',
    agency: A.highlands,
    beds: null,
    amenities: ['water', 'power'],
    photo: 'listing-plot-estate',
  },
  {
    id: 'wg-kakamega-plot',
    intent: 'land',
    type: 'plot-residential',
    county: 'kakamega',
    area: 'Lurambi',
    status: 'vacant',
    publishedAt: '2026-09-01',
    coordinates: { lat: 0.2916, lng: 34.7351 },
    chip: 'Plot · For sale',
    priceKes: 1_300_000,
    title: '50 by 100 plot in Lurambi, Kakamega, near the county hospital',
    meta: '50×100 · residential · ready title',
    location: 'Lurambi, Kakamega',
    agency: A.westernGate,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-plot-estate',
  },
  {
    id: 'rl-kajiado-agri',
    intent: 'land',
    type: 'plot-agricultural',
    county: 'kajiado',
    area: 'Kajiado town',
    status: 'vacant',
    publishedAt: '2026-08-26',
    coordinates: { lat: -1.8524, lng: 36.7768 },
    chip: 'Land · For sale',
    priceKes: 2_800_000,
    title: 'Five acres of agricultural land outside Kajiado town, fenced',
    meta: '5 acres · agricultural · ready title',
    location: 'Kajiado town, Kajiado',
    agency: A.savannah,
    beds: null,
    amenities: [],
    photo: 'listing-farmland',
  },

  // ---- Lease land (yearly) ----
  {
    id: 'sl-isinya-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'kajiado',
    area: 'Isinya',
    status: 'vacant',
    publishedAt: '2026-09-12',
    coordinates: { lat: -1.67, lng: 36.85 },
    chip: 'Farmland · To lease',
    priceKes: 120_000,
    title: 'Five acres of fenced farmland with a borehole',
    meta: '5 acres · agricultural · 3-year term',
    location: 'Isinya, Kajiado',
    agency: A.savannah,
    beds: null,
    amenities: ['water'],
    photo: 'listing-farmland',
  },
  {
    id: 'mh-athi-commercial',
    intent: 'lease',
    type: 'plot-commercial',
    county: 'machakos',
    area: 'Athi River',
    status: 'vacant',
    publishedAt: '2026-09-06',
    coordinates: { lat: -1.456, lng: 36.978 },
    chip: 'Commercial plot · To lease',
    priceKes: 650_000,
    title: 'One-acre commercial plot beside the highway',
    meta: '1 acre · commercial · 5-year term',
    location: 'Athi River, Machakos',
    agency: A.mavoko,
    beds: null,
    amenities: ['tarmac', 'power'],
    photo: 'listing-commercial-plot',
  },
  {
    id: 'rp-juja-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'kiambu',
    area: 'Juja',
    status: 'vacant',
    publishedAt: '2026-09-09',
    coordinates: { lat: -1.102, lng: 37.014 },
    chip: 'Farmland · To lease',
    priceKes: 40_000,
    title: 'Two acres for horticulture, river frontage',
    meta: '2 acres · agricultural · 1-year term',
    location: 'Juja, Kiambu',
    agency: A.ridgeways,
    beds: null,
    amenities: ['water'],
    photo: 'listing-farmland',
  },
  {
    id: 'rv-nakuru-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'nakuru',
    area: 'Njoro',
    status: 'vacant',
    publishedAt: '2026-08-29',
    coordinates: { lat: -0.3372, lng: 35.9439 },
    chip: 'Farmland · To lease',
    priceKes: 180_000,
    title: 'Ten acres of arable land in Njoro, tractor access, seasonal stream',
    meta: '10 acres · agricultural · 3-year term',
    location: 'Njoro, Nakuru',
    agency: A.rift,
    beds: null,
    amenities: ['water'],
    photo: 'listing-farmland',
  },
  {
    id: 'hp-eldoret-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'uasin-gishu',
    area: 'Moiben',
    status: 'vacant',
    publishedAt: '2026-09-03',
    coordinates: { lat: 0.6614, lng: 35.4139 },
    chip: 'Farmland · To lease',
    priceKes: 240_000,
    title: 'Fifteen acres of maize land in Moiben with all-weather road access',
    meta: '15 acres · agricultural · 2-year term',
    location: 'Moiben, Uasin Gishu',
    agency: A.highlands,
    beds: null,
    amenities: ['tarmac'],
    photo: 'listing-farmland',
  },
  {
    id: 'mk-timau-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'meru',
    area: 'Timau',
    status: 'booked',
    publishedAt: '2026-08-24',
    coordinates: { lat: 0.0833, lng: 37.2333 },
    chip: 'Farmland · To lease',
    priceKes: 95_000,
    title: 'Three acres in Timau for horticulture, with irrigation water rights',
    meta: '3 acres · agricultural · 1-year term',
    location: 'Timau, Meru',
    agency: A.mtKenya,
    beds: null,
    amenities: ['water'],
    photo: 'listing-farmland',
  },
  {
    id: 'ls-ahero-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'kisumu',
    area: 'Ahero',
    status: 'vacant',
    publishedAt: '2026-09-07',
    coordinates: { lat: -0.1735, lng: 34.9201 },
    chip: 'Farmland · To lease',
    priceKes: 60_000,
    title: 'Four acres of irrigated rice land in Ahero, scheme access',
    meta: '4 acres · agricultural · 1-year term',
    location: 'Ahero, Kisumu',
    agency: A.lakeside,
    beds: null,
    amenities: ['water'],
    photo: 'listing-lakeside',
  },
  {
    id: 'bc-kwale-commercial',
    intent: 'lease',
    type: 'plot-commercial',
    county: 'kwale',
    area: 'Ukunda',
    status: 'vacant',
    publishedAt: '2026-08-31',
    coordinates: { lat: -4.2874, lng: 39.5666 },
    chip: 'Commercial plot · To lease',
    priceKes: 420_000,
    title: 'Half-acre commercial plot on the Diani beach road, ideal for a shop row',
    meta: '1/2 acre · commercial · 5-year term',
    location: 'Ukunda, Kwale',
    agency: A.pwani,
    beds: null,
    amenities: ['tarmac', 'power'],
    photo: 'listing-commercial-plot',
  },
  {
    id: 'wg-bungoma-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    county: 'bungoma',
    area: 'Kimilili',
    status: 'vacant',
    publishedAt: '2026-08-22',
    coordinates: { lat: 0.7857, lng: 34.7169 },
    chip: 'Farmland · To lease',
    priceKes: 70_000,
    title: 'Six acres in Kimilili suited to maize and dairy fodder, fenced',
    meta: '6 acres · agricultural · 2-year term',
    location: 'Kimilili, Bungoma',
    agency: A.westernGate,
    beds: null,
    amenities: [],
    photo: 'listing-farmland',
  },

  // ---- Short stay (nightly) ----
  {
    id: 'ns-kilimani-short',
    intent: 'short-stay',
    type: 'unit-1bed',
    county: 'nairobi',
    area: 'Kilimani',
    status: 'vacant',
    publishedAt: '2026-09-14',
    coordinates: { lat: -1.291, lng: 36.787 },
    chip: 'Short stay · Furnished',
    priceKes: 6_500,
    title: 'Serviced one-bedroom, nightly or weekly',
    meta: '1 bed · sleeps 2 · Wi-Fi',
    location: 'Kilimani, Nairobi',
    agency: A.stays,
    beds: 1,
    amenities: ['water', 'power', 'parking'],
    photo: 'listing-furnished',
  },
  {
    id: 'ns-westlands-short',
    intent: 'short-stay',
    type: 'unit-2bed',
    county: 'nairobi',
    area: 'Westlands',
    status: 'vacant',
    publishedAt: '2026-09-10',
    coordinates: { lat: -1.265, lng: 36.805 },
    chip: 'Short stay · Furnished',
    priceKes: 9_500,
    title: 'Two-bedroom serviced apartment with gym, pool and housekeeping',
    meta: '2 bed · sleeps 4 · Wi-Fi',
    location: 'Westlands, Nairobi',
    agency: A.stays,
    beds: 2,
    amenities: ['gym', 'pool', 'parking', 'power'],
    photo: 'listing-furnished',
  },
  {
    id: 'ns-kileleshwa-studio',
    intent: 'short-stay',
    type: 'unit-bedsitter',
    county: 'nairobi',
    area: 'Kileleshwa',
    status: 'vacant',
    publishedAt: '2026-09-05',
    coordinates: { lat: -1.28, lng: 36.78 },
    chip: 'Short stay · Studio',
    priceKes: 4_500,
    title: 'Furnished studio for business travellers, fast Wi-Fi and workspace',
    meta: 'Studio · sleeps 2 · Wi-Fi',
    location: 'Kileleshwa, Nairobi',
    agency: A.stays,
    beds: null,
    amenities: ['power', 'parking'],
    photo: 'listing-furnished',
  },
  {
    id: 'pw-diani-short',
    intent: 'short-stay',
    type: 'unit-2bed',
    county: 'kwale',
    area: 'Diani',
    status: 'vacant',
    publishedAt: '2026-09-13',
    coordinates: { lat: -4.28, lng: 39.59 },
    chip: 'Short stay · Beach',
    priceKes: 12_000,
    title: 'Two-bedroom beach cottage in Diani with a shared pool, steps from the sand',
    meta: '2 bed · sleeps 4 · pool',
    location: 'Diani, Kwale',
    agency: A.pwani,
    beds: 2,
    amenities: ['pool', 'gated', 'parking'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'bc-nyali-short',
    intent: 'short-stay',
    type: 'unit-1bed',
    county: 'mombasa',
    area: 'Nyali',
    status: 'booked',
    publishedAt: '2026-09-08',
    coordinates: { lat: -4.04, lng: 39.71 },
    chip: 'Short stay · Furnished',
    priceKes: 7_000,
    title: 'One-bedroom furnished apartment in Nyali with sea view and standby generator',
    meta: '1 bed · sleeps 2 · Wi-Fi',
    location: 'Nyali, Mombasa',
    agency: A.bahari,
    beds: 1,
    amenities: ['power', 'pool', 'parking'],
    photo: 'listing-apartment-coast',
  },
  {
    id: 'pw-watamu-short',
    intent: 'short-stay',
    type: 'home-standalone',
    county: 'kilifi',
    area: 'Watamu',
    status: 'vacant',
    publishedAt: '2026-09-02',
    coordinates: { lat: -3.3556, lng: 40.0167 },
    chip: 'Short stay · Villa',
    priceKes: 25_000,
    title: 'Three-bedroom villa in Watamu with private pool and housekeeper',
    meta: '3 bed · sleeps 6 · private pool',
    location: 'Watamu, Kilifi',
    agency: A.pwani,
    beds: 3,
    amenities: ['pool', 'gated', 'parking', 'power'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'ls-kisumu-short',
    intent: 'short-stay',
    type: 'unit-1bed',
    county: 'kisumu',
    area: 'Milimani',
    status: 'vacant',
    publishedAt: '2026-08-30',
    coordinates: { lat: -0.1, lng: 34.76 },
    chip: 'Short stay · Furnished',
    priceKes: 5_000,
    title: 'One-bedroom furnished apartment in Milimani, Kisumu, near the lakefront',
    meta: '1 bed · sleeps 2 · Wi-Fi',
    location: 'Milimani, Kisumu',
    agency: A.lakeside,
    beds: 1,
    amenities: ['parking', 'water'],
    photo: 'listing-furnished',
  },
  {
    id: 'mk-nanyuki-short',
    intent: 'short-stay',
    type: 'home-standalone',
    county: 'laikipia',
    area: 'Nanyuki',
    status: 'vacant',
    publishedAt: '2026-09-11',
    coordinates: { lat: 0.01, lng: 37.07 },
    chip: 'Short stay · Cottage',
    priceKes: 8_500,
    title: 'Two-bedroom cottage outside Nanyuki with fireplace and Mount Kenya view',
    meta: '2 bed · sleeps 4 · fireplace',
    location: 'Nanyuki, Laikipia',
    agency: A.mtKenya,
    beds: 2,
    amenities: ['parking', 'water'],
    photo: 'listing-nanyuki-view',
  },
  {
    id: 'rv-naivasha-short',
    intent: 'short-stay',
    type: 'home-standalone',
    county: 'nakuru',
    area: 'Naivasha',
    status: 'vacant',
    publishedAt: '2026-09-04',
    coordinates: { lat: -0.78, lng: 36.38 },
    chip: 'Short stay · Lakeside',
    priceKes: 11_000,
    title: 'Three-bedroom lakeside house on Moi South Lake Road with a garden',
    meta: '3 bed · sleeps 6 · garden',
    location: 'Naivasha, Nakuru',
    agency: A.rift,
    beds: 3,
    amenities: ['parking', 'gated', 'water'],
    photo: 'listing-standalone-home',
  },
  {
    id: 'hp-eldoret-short',
    intent: 'short-stay',
    type: 'unit-2bed',
    county: 'uasin-gishu',
    area: 'Elgon View',
    status: 'vacant',
    publishedAt: '2026-08-27',
    coordinates: { lat: 0.5, lng: 35.28 },
    chip: 'Short stay · Furnished',
    priceKes: 6_000,
    title: 'Two-bedroom furnished apartment in Elgon View, Eldoret, with parking',
    meta: '2 bed · sleeps 4 · Wi-Fi',
    location: 'Elgon View, Eldoret',
    agency: A.highlands,
    beds: 2,
    amenities: ['parking', 'power'],
    photo: 'listing-furnished',
  },
];

/** Reference date for "listed N days ago" style copy; sample data never reads the clock. */
export const listingsAsOf = '2026-09-16';

export const marketplaceCopy = {
  title: 'Marketplace — units, homes and plots across Kenya',
  description:
    'Units, homes and plots anywhere in Kenya, listed by the organizations that manage them. Book a viewing on WhatsApp.',
  resultsSuffix: 'results · sample data',
  lede: 'Every listing comes from the organization that manages it',
  clearAll: 'Clear all',
  sort: 'Sort',
  filters: 'Filters',
  status: 'Status',
  location: 'Location',
  bedrooms: 'Bedrooms',
  amenities: 'Amenities',
  showResults: 'Show results',
  emptyTitle:
    'Nothing listed for this search yet — widen your budget, try another county, or get a WhatsApp alert when one lists.',
  widenBudget: 'Widen budget',
  getAlert: 'Get WhatsApp alert',
  alertsTitle: 'Want the next one before everyone else?',
  alertsBody:
    "Save this search and we'll WhatsApp you the moment an agency lists a match. No app, no email.",
  alertsCta: 'Get WhatsApp alerts',
  alertsFor: 'Get WhatsApp alerts for this search',
  note: 'Prices and listings shown are samples for illustration.',
  nearestNote: 'Nearest needs your location; showing newest first for now.',
  viewingCta: 'Book a viewing',
  whatsappCta: 'WhatsApp',
  listedPrefix: 'Listed',
  openMap: 'Open in Google Maps',
  statusLabels: {
    vacant: 'Vacant',
    booked: 'Booked',
    let: 'Let',
    'under-offer': 'Under offer',
    sold: 'Sold',
    'coming-soon': 'Coming soon',
  } satisfies Record<ListingStatus, string>,
  amenityLabels: {
    water: 'Borehole / water backup',
    parking: 'Parking',
    power: 'Backup generator',
    gated: 'Gated with 24-hour security',
    tarmac: 'Tarmac access',
    matatu: 'Near matatu route',
    lift: 'Lift',
    gym: 'Gym',
    pool: 'Swimming pool',
  } satisfies Record<MarketplaceAmenity, string>,
} as const;
