import type {
  MarketplaceAmenity,
  MarketplaceIntent,
  MarketplaceType,
  MarketplaceWhere,
} from '@ethanel/contracts/marketplace-search';

/**
 * Sample listings for the Sprint 001 marketplace, from the canvas. Labelled "sample" wherever
 * they render. listing-svc replaces this module; the shape is what its /v1/listings returns.
 * `priceKes` is a whole-shilling display figure for filtering sample data only; ledger money is
 * bigint minor units everywhere else (see AGENTS.md rule 4).
 */
export interface SampleListing {
  readonly id: string;
  readonly intent: MarketplaceIntent;
  readonly type: MarketplaceType;
  readonly where: MarketplaceWhere;
  readonly chip: string;
  readonly priceKes: number;
  readonly title: string;
  readonly meta: string;
  readonly location: string;
  readonly agency: string;
  readonly beds: number | null;
  readonly amenities: readonly MarketplaceAmenity[];
  /** Days since listed; lower is newer. Sample ordering only. */
  readonly listedDaysAgo: number;
  readonly photo: 'a' | 'b' | 'c';
}

export const sampleListings: readonly SampleListing[] = [
  {
    id: 'rl-kilimani-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    where: 'nairobi-kilimani',
    chip: '2-bed unit · To let',
    priceKes: 45_000,
    title: 'Bright two-bedroom with balcony, borehole water',
    meta: '2 bed · 2 bath · 90 m²',
    location: 'Kilimani, Nairobi',
    agency: 'Riverside Lettings',
    beds: 2,
    amenities: ['water', 'parking'],
    listedDaysAgo: 1,
    photo: 'a',
  },
  {
    id: 'rp-ruaka-1bed',
    intent: 'rent',
    type: 'unit-1bed',
    where: 'nairobi-ruaka',
    chip: '1-bed unit · To let',
    priceKes: 25_000,
    title: 'One-bedroom in a gated court, near matatu route',
    meta: '1 bed · 1 bath · 48 m²',
    location: 'Ruaka, Kiambu',
    agency: 'Ridgeways Property Care',
    beds: 1,
    amenities: ['gated', 'matatu'],
    listedDaysAgo: 3,
    photo: 'b',
  },
  {
    id: 'mh-syokimau-3bed',
    intent: 'rent',
    type: 'home-maisonette',
    where: 'machakos-syokimau',
    chip: '3-bed home · To let',
    priceKes: 65_000,
    title: 'Three-bedroom maisonette with parking and backup power',
    meta: '3 bed · 3 bath · 140 m²',
    location: 'Syokimau, Machakos',
    agency: 'Mavoko Homes',
    beds: 3,
    amenities: ['parking', 'power', 'gated'],
    listedDaysAgo: 5,
    photo: 'c',
  },
  {
    id: 'rl-westlands-bedsitter',
    intent: 'rent',
    type: 'unit-bedsitter',
    where: 'nairobi-westlands',
    chip: 'Bedsitter · To let',
    priceKes: 18_000,
    title: 'Furnished bedsitter, water and Wi-Fi included',
    meta: 'Studio · 1 bath · 28 m²',
    location: 'Westlands, Nairobi',
    agency: 'Riverside Lettings',
    beds: null,
    amenities: ['water'],
    listedDaysAgo: 2,
    photo: 'a',
  },
  {
    id: 'ns-kilimani-short',
    intent: 'short-stay',
    type: 'unit-1bed',
    where: 'nairobi-kilimani',
    chip: 'Short stay · Furnished',
    priceKes: 6_500,
    title: 'Serviced one-bedroom, nightly or weekly',
    meta: '1 bed · sleeps 2 · Wi-Fi',
    location: 'Kilimani, Nairobi',
    agency: 'Nairobi Stays Co.',
    beds: 1,
    amenities: ['water', 'power', 'parking'],
    listedDaysAgo: 4,
    photo: 'b',
  },
  {
    id: 'rg-rongai-2bed',
    intent: 'rent',
    type: 'unit-2bed',
    where: 'kajiado-ongata-rongai',
    chip: '2-bed unit · To let',
    priceKes: 38_000,
    title: 'Two-bedroom apartment, gated with 24-hour security',
    meta: '2 bed · 1 bath · 82 m²',
    location: 'Ongata Rongai, Kajiado',
    agency: 'Rongai Lettings',
    beds: 2,
    amenities: ['gated', 'parking'],
    listedDaysAgo: 7,
    photo: 'c',
  },
  {
    id: 'kh-ruiru-3bed',
    intent: 'sale',
    type: 'home-maisonette',
    where: 'kiambu-ruiru',
    chip: '3-bed home · For sale',
    priceKes: 9_800_000,
    title: 'Three-bedroom maisonette in a gated court',
    meta: '3 bed · 3 bath · 1/8 acre',
    location: 'Ruiru, Kiambu',
    agency: 'Kiambu Homes Agency',
    beds: 3,
    amenities: ['gated', 'parking', 'water'],
    listedDaysAgo: 2,
    photo: 'a',
  },
  {
    id: 'rg-rongai-4bed',
    intent: 'sale',
    type: 'home-maisonette',
    where: 'kajiado-ongata-rongai',
    chip: '4-bed home · For sale',
    priceKes: 14_500_000,
    title: 'Four-bedroom townhouse with DSQ and garden',
    meta: '4 bed · 4 bath · 1/4 acre',
    location: 'Ongata Rongai, Kajiado',
    agency: 'Rongai Lettings',
    beds: 4,
    amenities: ['gated', 'parking', 'power'],
    listedDaysAgo: 9,
    photo: 'b',
  },
  {
    id: 'kh-thika-2bed',
    intent: 'sale',
    type: 'unit-2bed',
    where: 'kiambu-thika',
    chip: '2-bed unit · For sale',
    priceKes: 5_200_000,
    title: 'Two-bedroom apartment, ready title, lift and parking',
    meta: '2 bed · 2 bath · 78 m²',
    location: 'Thika, Kiambu',
    agency: 'Kiambu Homes Agency',
    beds: 2,
    amenities: ['parking'],
    listedDaysAgo: 6,
    photo: 'c',
  },
  {
    id: 'sl-kitengela-plot',
    intent: 'land',
    type: 'plot-residential',
    where: 'kajiado-kitengela',
    chip: 'Plot · For sale',
    priceKes: 2_400_000,
    title: '1/8 acre residential plot, tarmac access',
    meta: '1/8 acre · residential · ready title',
    location: 'Kitengela, Kajiado',
    agency: 'Savannah Land Co.',
    beds: null,
    amenities: ['tarmac'],
    listedDaysAgo: 1,
    photo: 'a',
  },
  {
    id: 'sl-kangundo-plot',
    intent: 'land',
    type: 'plot-residential',
    where: 'machakos-kangundo-road',
    chip: 'Plot · For sale',
    priceKes: 1_650_000,
    title: '1/4 acre plot with water and power on the boundary',
    meta: '1/4 acre · residential · ready title',
    location: 'Kangundo Road, Machakos',
    agency: 'Savannah Land Co.',
    beds: null,
    amenities: ['water', 'power'],
    listedDaysAgo: 8,
    photo: 'b',
  },
  {
    id: 'kh-ruiru-plot',
    intent: 'land',
    type: 'plot-residential',
    where: 'kiambu-ruiru',
    chip: 'Plot · For sale',
    priceKes: 4_900_000,
    title: '50 by 100 plot in a controlled estate',
    meta: '50×100 · residential · ready title',
    location: 'Ruiru, Kiambu',
    agency: 'Kiambu Homes Agency',
    beds: null,
    amenities: ['gated', 'tarmac'],
    listedDaysAgo: 12,
    photo: 'c',
  },
  {
    id: 'sl-isinya-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    where: 'kajiado-isinya',
    chip: 'Farmland · To lease',
    priceKes: 120_000,
    title: 'Five acres of fenced farmland with a borehole',
    meta: '5 acres · agricultural · 3-year term',
    location: 'Isinya, Kajiado',
    agency: 'Savannah Land Co.',
    beds: null,
    amenities: ['water'],
    listedDaysAgo: 3,
    photo: 'a',
  },
  {
    id: 'mh-athi-commercial',
    intent: 'lease',
    type: 'plot-commercial',
    where: 'machakos-athi-river',
    chip: 'Commercial plot · To lease',
    priceKes: 650_000,
    title: 'One-acre commercial plot beside the highway',
    meta: '1 acre · commercial · 5-year term',
    location: 'Athi River, Machakos',
    agency: 'Mavoko Homes',
    beds: null,
    amenities: ['tarmac', 'power'],
    listedDaysAgo: 10,
    photo: 'b',
  },
  {
    id: 'rp-juja-farm',
    intent: 'lease',
    type: 'plot-agricultural',
    where: 'kiambu-juja',
    chip: 'Farmland · To lease',
    priceKes: 40_000,
    title: 'Two acres for horticulture, river frontage',
    meta: '2 acres · agricultural · 1-year term',
    location: 'Juja, Kiambu',
    agency: 'Ridgeways Property Care',
    beds: null,
    amenities: ['water'],
    listedDaysAgo: 4,
    photo: 'c',
  },
];

export const marketplaceCopy = {
  title: 'Marketplace — units, homes and plots across Kenya',
  description:
    'Units, homes and plots listed by the organizations that manage them. Book a viewing on WhatsApp.',
  resultsSuffix: 'results · sample data',
  lede: 'Every listing comes from the organization that manages it',
  clearAll: 'Clear all',
  sort: 'Sort',
  filters: 'Filters',
  location: 'Location',
  bedrooms: 'Bedrooms',
  amenities: 'Amenities',
  showResults: 'Show results',
  emptyTitle:
    'Nothing listed for this search yet — widen your budget or get a WhatsApp alert when one lists.',
  widenBudget: 'Widen budget',
  getAlert: 'Get WhatsApp alert',
  alertsTitle: 'Want the next one before everyone else?',
  alertsBody:
    "Save this search and we'll WhatsApp you the moment an agency lists a match. No app, no email.",
  alertsCta: 'Get WhatsApp alerts',
  alertsFor: 'Get WhatsApp alerts for this search',
  note: 'Prices and listings shown are samples for illustration.',
  nearestNote: 'Nearest needs your location; showing newest first for now.',
  viewingCta: 'Book a viewing',
  whatsappCta: 'WhatsApp',
  amenityLabels: {
    water: 'Borehole / water backup',
    parking: 'Parking',
    power: 'Backup power',
    gated: 'Gated court',
    tarmac: 'Tarmac access',
    matatu: 'Near matatu route',
  } satisfies Record<MarketplaceAmenity, string>,
} as const;
